PRINT_EMP MACRO E_ID, E_NAME, E_DEPT, E_AGE
    LEA DX, E_ID
    MOV AH, 09H
    INT 21H
    CALL NEXTLINE
    LEA DX, E_NAME
    MOV AH, 09H
    INT 21H
    CALL NEXTLINE
    LEA DX, E_DEPT
    MOV AH, 09H
    INT 21H
    CALL NEXTLINE
    LEA DX, E_AGE
    MOV AH, 09H
    INT 21H
ENDM

DATA SEGMENT
    EMP_ID    DB 'EMP ID:       0008$'
    EMP_NAME  DB 'EMP NAME:     Saqlain ALi Sajid$'
    EMP_DEPT  DB 'DEPARTMENT:   Software Engineer$'
    EMP_AGE   DB 'AGE:          21$'
DATA ENDS
STACK SEGMENT
    DW 128 DUP(0)
STACK ENDS
CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX

    ; CALL MACRO
    PRINT_EMP EMP_ID, EMP_NAME, EMP_DEPT, EMP_AGE

    ; EXIT PROGRAM
    MOV AX, 4C00H
    INT 21H
CODE ENDS

NEXTLINE PROC
    MOV AH, 02H
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    RET
NEXTLINE ENDP

END START